export enum ShopeeOrderStatus {
  UNPAID ='UNPAID',
  READY_TO_SHIP ='READY_TO_SHIP',
  RETRY_SHIP ='RETRY_SHIP',
  SHIPPED ='SHIPPED',
  TO_CONFIRM_RECEIVE ='TO_CONFIRM_RECEIVE',
  IN_CANCEL ='IN_CANCEL',
  CANCELLED ='CANCELLED',
  TO_RETURN ='TO_RETURN',
  COMPLETED ='COMPLETED',
}